<?php

    echo "<h1>Coypright !</h1>";

    echo "<h3>Praeteritis, inquit, gaudeo.</h3>";

    echo "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ex quo intellegitur idem illud, solum bonum esse, quod honestum sit, idque esse beate vivere: honeste, id est cum virtute, vivere. Cur, nisi quod turpis oratio est? Non autem hoc: igitur ne illud quidem. Duo Reges: constructio interrete. Ergo, si semel tristior effectus est, hilara vita amissa est? Nam neque virtute retinetur ille in vita, nec iis, qui sine virtute sunt, mors est oppetenda. Et quae per vim oblatum stuprum volontaria morte lueret inventa est et qui interficeret filiam, ne stupraretur. Tu autem inter haec tantam multitudinem hominum interiectam non vides nec laetantium nec dolentium? Compensabatur, inquit, cum summis doloribus laetitia. Nihilo beatiorem esse Metellum quam Regulum. </p>";

    echo "<p>Quamquam ab iis philosophiam et omnes ingenuas disciplinas habemus; Quare si potest esse beatus is, qui est in asperis reiciendisque rebus, potest is quoque esse. Vitiosum est enim in dividendo partem in genere numerare. Quae cum dixissem, Habeo, inquit Torquatus, ad quos ista referam, et, quamquam aliquid ipse poteram, tamen invenire malo paratiores. Neque solum ea communia, verum etiam paria esse dixerunt. Nos commodius agimus. Experiamur igitur, inquit, etsi habet haec Stoicorum ratio difficilius quiddam et obscurius. Nihilne est in his rebus, quod dignum libero aut indignum esse ducamus? Quae cum essent dicta, discessimus. </p>";

    echo "<p>Cuius quidem, quoniam Stoicus fuit, sententia condemnata mihi videtur esse inanitas ista verborum.</p>";

    echo "<p>Tu vero, inquam, ducas licet, si sequetur; Idem fecisset Epicurus, si sententiam hanc, quae nunc Hieronymi est, coniunxisset cum Aristippi vetere sententia. Si enim ad populum me vocas, eum. Atqui iste locus est, Piso, tibi etiam atque etiam confirmandus, inquam; Habent enim et bene longam et satis litigiosam disputationem. Nummus in Croesi divitiis obscuratur, pars est tamen divitiarum. Quin etiam ferae, inquit Pacuvius, quíbus abest, ad praécavendum intéllegendi astútia, iniecto terrore mortis horrescunt. In his igitur partibus duabus nihil erat, quod Zeno commutare gestiret. Nemo nostrum istius generis asotos iucunde putat vivere. Non ergo Epicurus ineruditus, sed ii indocti, qui, quae pueros non didicisse turpe est, ea putant usque ad senectutem esse discenda. </p>";

    echo "<p>E quo efficitur, non ut nos non intellegamus quae vis sit istius verbi, sed ut ille suo more loquatur, nostrum neglegat. Itaque quantum adiit periculum! ad honestatem enim illum omnem conatum suum referebat, non ad voluptatem. Qui autem de summo bono dissentit de tota philosophiae ratione dissentit. Bestiarum vero nullum iudicium puto. Quod dicit Epicurus etiam de voluptate, quae minime sint voluptates, eas obscurari saepe et obrui. An obliviscimur, quantopere in audiendo in legendoque moveamur, cum pie, cum amice, cum magno animo aliquid factum cognoscimus? Decius, princeps in ea familia consulatus, cum se devoverat et equo admisso in mediam aciem Latinorum irruebat, aliquid de voluptatibus suis cogitabat? Maximeque eos videre possumus res gestas audire et legere velle, qui a spe gerendi absunt confecti senectute. Atque ab his initiis profecti omnium virtutum et originem et progressionem persecuti sunt. Cum enim summum bonum in voluptate ponat, negat infinito tempore aetatis voluptatem fieri maiorem quam finito atque modico. Virtutibus igitur rectissime mihi videris et ad consuetudinem nostrae orationis vitia posuisse contraria. </p>";

    echo "<p>Quae est quaerendi ac disserendi, quae logikh dicitur, iste vester plane, ut mihi quidem videtur, inermis ac nudus est. Non autem hoc: igitur ne illud quidem. Quae contraria sunt his, malane? Vives, inquit Aristo, magnifice atque praeclare, quod erit cumque visum ages, numquam angere, numquam cupies, numquam timebis. In schola desinis. Cum ageremus, inquit, vitae beatum et eundem supremum diem, scribebamus haec. Et quis a Stoicis et quem ad modum diceretur, tamen ego quoque exponam, ut perspiciamus, si potuerimus, quidnam a Zenone novi sit allatum. Cum autem venissemus in Academiae non sine causa nobilitata spatia, solitudo erat ea, quam volueramus. Huius ego nunc auctoritatem sequens idem faciam. Quod cum dixissent, ille contra. Ita graviter et severe voluptatem secrevit a bono. Non quaero, quid dicat, sed quid convenienter possit rationi et sententiae suae dicere. </p>";

    echo "<h3>In eo enim positum est id, quod dicimus esse expetendum.</h3>";

    echo "<p>Polemoni et iam ante Aristoteli ea prima visa sunt, quae paulo ante dixi. Restincta enim sitis stabilitatem voluptatis habet, inquit, illa autem voluptas ipsius restinctionis in motu est. Ita multa dicunt, quae vix intellegam. Qui ita affectus, beatum esse numquam probabis; Atque his de rebus et splendida est eorum et illustris oratio. Falli igitur possumus. Quae similitudo in genere etiam humano apparet. Quo plebiscito decreta a senatu est consuli quaestio Cn. Animum autem reliquis rebus ita perfecit, ut corpus; Quid autem habent admirationis, cum prope accesseris? </p>";

    echo "<p>Immo sit sane nihil melius, inquam-nondum enim id quaero-, num propterea idem voluptas est, quod, ut ita dicam, indolentia? Hoc enim identidem dicitis, non intellegere nos quam dicatis voluptatem. Atque ut a corpore ordiar, videsne ut, si quae in membris prava aut debilitata aut inminuta sint, occultent homines? Nosti, credo, illud: Nemo pius est, qui pietatem-; Ubi ut eam caperet aut quando? Hunc vos beatum; Dic in quovis conventu te omnia facere, ne doleas. Sin kakan malitiam dixisses, ad aliud nos unum certum vitium consuetudo Latina traduceret. </p>";

    echo "<p>An potest, inquit ille, quicquam esse suavius quam nihil dolere? Nunc haec primum fortasse audientis servire debemus. Stoici restant, ei quidem non unam aliquam aut alteram rem a nobis, sed totam ad se nostram philosophiam transtulerunt; Nam et a te perfici istam disputationem volo, nec tua mihi oratio longa videri potest. Suo genere perveniant ad extremum; </p>";

    echo "<p>Faceres tu quidem, Torquate, haec omnia; Nulla erit controversia. Etsi ea quidem, quae adhuc dixisti, quamvis ad aetatem recte isto modo dicerentur. Quid autem habent admirationis, cum prope accesseris? Nam his libris eum malo quam reliquo ornatu villae delectari. Cuius etiam illi hortuli propinqui non memoriam solum mihi afferunt, sed ipsum videntur in conspectu meo ponere. Illa enim, quae prosunt aut quae nocent, aut bona sunt aut mala, quae sint paria necesse est. Sed emolumenta communia esse dicuntur, recte autem facta et peccata non habentur communia. Somnum denique nobis, nisi requietem corporibus et is medicinam quandam laboris afferret, contra naturam putaremus datum; Possumusne ergo in vita summum bonum dicere, cum id ne in cena quidem posse videamur? Earum etiam rerum, quas terra gignit, educatio quaedam et perfectio est non dissimilis animantium. Quibus natura iure responderit non esse verum aliunde finem beate vivendi, a se principia rei gerendae peti; </p>";

    echo "<blockquote>Frater et T.</blockquote>";

    echo "<p>Illud dico, ea, quae dicat, praeclare inter se cohaerere. Cuius ad naturam apta ratio vera illa et summa lex a philosophis dicitur. Hoc uno captus Erillus scientiam summum bonum esse defendit nec rem ullam aliam per se expetendam. Nullum inveniri verbum potest quod magis idem declaret Latine, quod Graece, quam declarat voluptas. In schola desinis. Nec vero sum nescius esse utilitatem in historia, non modo voluptatem. Nec vero alia sunt quaerenda contra Carneadeam illam sententiam. Quibus natura iure responderit non esse verum aliunde finem beate vivendi, a se principia rei gerendae peti; Aut haec tibi, Torquate, sunt vituperanda aut patrocinium voluptatis repudiandum. Stoici restant, ei quidem non unam aliquam aut alteram rem a nobis, sed totam ad se nostram philosophiam transtulerunt; </p>";

?>
